<<<<<<< HEAD
name: Deploy del Extent Report
=======
name: Deploy Extent Report to GitHub Pages
>>>>>>> 21480cb1cef4e76fd1fe2bac3a2410344f85b9e5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout código
=======
      - name: Clonar repositorio
>>>>>>> 21480cb1cef4e76fd1fe2bac3a2410344f85b9e5
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
<<<<<<< HEAD
          java-version: '17'
          distribution: 'temurin'

      - name: Ejecutar pruebas
        run: ./gradlew clean test

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
=======
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar pruebas y generar reporte
        run: ./gradlew clean test

      - name: Publicar reporte en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
>>>>>>> 21480cb1cef4e76fd1fe2bac3a2410344f85b9e5
